#IMAGEN A UTILIZAR
FROM python:3.8 
#ETIQUETA
LABEL version = 1.0 

#CREACION DE DIRECTORIO DE TRABAJO 
RUN mkdir /app
#ESTABLECEMOS EL DIRECTORIO DE TRABAJO
WORKDIR /app
#COPIAMOS LOS ARCHIVOS LOCALES A NUESTRO CONTENEDOR
ADD . /app/

#INSTALAMOS LOS REQUISITOS DE LA APLICACION
RUN pip install -r requirements.txt

#DEFINIMOS LA VARIABLE DE ENTORNO FLASK_APP PARA LLAMARLA EN EL CMD
ENV FLASK_APP=app.py

#EXPONEMOS EL PUERTO A UTILIZAR
EXPOSE 5000

#DEFINIMOS EL ENTRYPOINT DESDE EL CUAL SE EJECUTARAN LOS COMANDOS DEL CMD
ENTRYPOINT ["python"]

#EJECUTAMOS LA APLICACION
CMD ["-m", "flask", "run", "--host", "0.0.0.0"]
#
